[build]
  command = "npm run build"
  publish = "dist"

# Custom Headers for .js and .jsx files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

# Custom Headers for security best practices
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"

# Specific redirects first
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301
  force = true

[[redirects]]
  from = "/old-blog/*"
  to = "/new-blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/maintenance"
  to = "/maintenance.html"
  status = 302
  force = true

# SPA fallback - This must be the last redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = true



